markdown: rdiscount
permalink: /:categories/:year/:month/:day/:title 
url: http://forwind.github.com
img_url: http://forwind.github.com/assets/images
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
auto: true
pygments: true
paginate: 20

# Themes are encouraged to use these universal variables 
# so be sure to set them if your theme uses them.
#
title : forwind.github.com
#tagline: Site Tagline
author : forwind
name : forwind
email : fengaipan@foxmail.com
github : forwind
qq : 992444214
duoshuo: forwind
weibo: 2754399277
#twitter : username
#feedburner : feedname
about : "This is my blog."

#production_url : http://username.github.io

  
